<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <AssemblyTitle>Windows Service Wrapper</AssemblyTitle>
    <Description>Allows arbitrary process to run as a Windows service by wrapping it.</Description>
    <Company>CloudBees, Inc.</Company>
    <Product>Windows Service Wrapper</Product>
    <Copyright>Copyright (c) 2008-2020 Kohsuke Kawaguchi, Sun Microsystems, Inc., CloudBees, Inc., Oleg Nenashev and other contributors</Copyright>
  </PropertyGroup>

  <PropertyGroup>
    <DebuggerSupport>false</DebuggerSupport>
    <NullabilityInfoContextSupport>false</NullabilityInfoContextSupport>
  </PropertyGroup>

  <PropertyGroup Condition="'$(RuntimeIdentifier)' != ''">
    <PublishSingleFile>true</PublishSingleFile>
    <TrimMode>partial</TrimMode>
    <_AggressiveAttributeTrimming>true</_AggressiveAttributeTrimming>
    <PublishTrimmed>true</PublishTrimmed>
  </PropertyGroup>

  <PropertyGroup>
    <RollForward>Major</RollForward>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WinSW.Core\WinSW.Core.csproj" />
    <ProjectReference Include="..\WinSW.Plugins\WinSW.Plugins.csproj" />
  </ItemGroup>

  <Target Name="PublishCoreExe" AfterTargets="Publish">

    <MakeDir Directories="$(ArtifactsPublishDir)" />
    <Copy SourceFiles="$(PublishDir)$(TargetName).exe" DestinationFiles="$(ArtifactsPublishDir)WinSW-$(PlatformTarget).exe" />

  </Target>

</Project>
